export const userInputs = [
  {
    id: 1,
    label: "Username",
    type: "text",
    placeholder: "john_doe",
    name: "username",
    options: [],
  },
  {
    id: 2,
    label: "Full Name",
    type: "text",
    placeholder: "John Doe",
    name: "fullname",
    options: [],
  },
  {
    id: 3,
    label: "Email",
    type: "mail",
    name: "email",
    placeholder: "john_doe@gmail.com",
    options: [],
  },
  {
    id: 4,
    label: "Phone",
    type: "text",
    placeholder: "+1 234 567 89",
    name: "phonenumber",
    options: [],
  },
  {
    id: 5,
    label: "Password",
    type: "password",
    name: "password",
    options: [],
  },
  {
    id: 6,
    label: "Address",
    type: "text",
    placeholder: "Elton St. 216 NewYork",
    name: "address",
    options: [],
  },
  {
    id: 7,
    label: "Country",
    type: "text",
    placeholder: "USA",
    name: "country",
    options: [],
  },
  {
    id: 8,
    label: "Title",
    type: "text",
    placeholder: "Manager",
    name: "title",
    options: [
      {
        id: 1,
        label: "Choose your selection",
        value: "",
      },
      {
        id: 2,
        label: "Admin",
        value: "admin",
      },
      {
        id: 3,
        label: "Manager",
        value: "manager",
      },
      {
        id: 4,
        label: "Employee",
        value: "employee",
      }
    ],
  },
  {
    id: 9,
    label: "Professional",
    type: "text",
    placeholder: "Accounting",
    name: "professional",
    options: [
      {
        id: 1,
        label: "Choose your selection",
        value: "",
      },
      {
        id: 2,
        label: "Admin",
        value: "admin",
      },
      {
        id: 3,
        label: "Manager",
        value: "manager",
      },
      {
        id: 4,
        label: "Accounting",
        value: "accounting",
      },
      {
        id: 5,
        label: "Software Engineering",
        value: "software engineering",
      },
      {
        id: 6,
        label: "Shipper",
        value: "shipper",
      },
    ],
  },
  {
    id: 10,
    label: "Status",
    type: "text",
    placeholder: "Active",
    name: "status",
    options: [
      {
        id: 1,
        label: "Choose your selection",
        value: "",
      },
      {
        id: 2,
        label: "Active",
        value: "active",
      },
      {
        id: 3,
        label: "Inactive",
        value: "inactive",
      },
      {
        id: 4,
        label: "Pending",
        value: "pending",
      },
    ],
  },
];

export const customerInputs = [
  {
    id: 1,
    label: "Username",
    type: "text",
    placeholder: "john_doe",
    name: "username",
    options: [],
  },
  {
    id: 2,
    label: "Full Name",
    type: "text",
    placeholder: "John Doe",
    name: "fullname",
    options: [],
  },
  {
    id: 3,
    label: "Email",
    type: "mail",
    name: "email",
    placeholder: "john_doe@gmail.com",
    options: [],
  },
  {
    id: 4,
    label: "Phone",
    type: "text",
    placeholder: "+1 234 567 89",
    name: "phonenumber",
    options: [],
  },
  {
    id: 5,
    label: "Password",
    type: "password",
    name: "password",
    options: [],
  },
  {
    id: 6,
    label: "Address",
    type: "text",
    placeholder: "Elton St. 216 NewYork",
    name: "address",
    options: [],
  },
  {
    id: 7,
    label: "Country",
    type: "text",
    placeholder: "USA",
    name: "country",
    options: [],
  },
  {
    id: 8,
    label: "Level",
    type: "text",
    placeholder: "beginner",
    name: "level",
    options: [],
  },
  {
    id: 9,
    label: "Scores",
    type: "text",
    placeholder: "0",
    name: "scores",
    options: [],
  },
];

export const productInputs = [
  {
    id: 1,
    label: "Title",
    type: "text",
    placeholder: "Apple Macbook Pro",
  },
  {
    id: 2,
    label: "Description",
    type: "text",
    placeholder: "Description",
  },
  {
    id: 3,
    label: "Category",
    type: "text",
    placeholder: "Computers",
  },
  {
    id: 4,
    label: "Price",
    type: "text",
    placeholder: "100",
  },
  {
    id: 5,
    label: "Stock",
    type: "text",
    placeholder: "in stock",
  },
];